### ISSUE TITLE
Selector syntax

### ISSUE THREAD

**Issue by jfgreffier** [jfgreffier/playwright-relative-selector#1]
The syntax of the playwright-relative-selector could be improved.

At the moment, the syntax is as follow
```
text="Click me" >> relative=toRightOf Middle
```
- `text="Click me"` is a Playwright selector
- `>>` is a chaining separator, see https://playwright.dev/#version=v1.4.2&path=docs%2Fselectors.md&q=chaining-selectors
- `relative=toRightOf Middle` is the actual playwright-relative-selector

What do you think ?
How do you feel about the usage of Playwright selector chaining ?

**Comment by idxn** [comment]
@jfgreffier what will the locator be if it's not the text? Will it be like this?
```
text="Click me" >> relative=toRightOf css=#testid
```

**Comment by roughsoft** [comment]
https://github.com/getgauge/taiko/wiki/Taiko's-Proximity-Selector

**Comment by roughsoft** [comment]
@jfgreffier  ref

**Comment by jfgreffier** [comment]
@idxn Very good question. So far, what you describe is not possible. What do you think if instead of a selector, I provide an helper function ?

```
const clickMeElement = await relativeSelector(page, 'text="Click me" toRightOf css=#testid');
await clickMeElement.click();
```

In this way we can use similar syntax to what you describe, and mix it with any Playwright selector.

**Comment by jfgreffier** [comment]
> https://github.com/getgauge/taiko/wiki/Taiko's-Proximity-Selector

@roughsoft Thanks for the reference, I found it very useful.

It made me realize few things :
- My home-made selector for text is crap
- Taiko's algorithm chose the closest element...
- ... which I can't implement with the chaining operator `>>` as in this case, the relative selector is called for each candidate.

**Comment by idxn** [comment]
@jfgreffier That's more than enough. :)

**Comment by jfgreffier** [comment]
The release with the new syntax is available !

**Comment by stordopoulos** [comment]
> The release with the new syntax is available !

Thanks for the update, @jfgreffier. Does that mean that the [playwright-relative-selector](https://www.npmjs.com/package/playwright-relative-selector) package is part of the official playwright release, with the same documentation?

Do you think there's can be a `near` selector next? It'll be fantastic if this could evolve into a full "black box" mode, similar to Taiko's.

**Comment by jfgreffier** [comment]
> Does that mean that the [playwright-relative-selector](https://www.npmjs.com/package/playwright-relative-selector) package is part of the official playwright release, with the same documentation?

No, it is not part of Playwright. I meant a new release of [playwright-relative-selector](https://www.npmjs.com/package/playwright-relative-selector) package with the new syntax is available.

Ultimately I'd like it to be part of Playwright, but it's still a long way to go. Support my project by giving a star and feedback like this !

> Do you think there's can be a near selector next? It'll be fantastic if this could evolve into a full "black box" mode, similar to Taiko's.

Feel free to create an issue. `near` selector is definitely in my mind, that's a great feedback.
