### ISSUE TITLE
[Feature] Near or Closest relative position selector

### ISSUE THREAD

**Issue by stordopoulos** [jfgreffier/playwright-relative-selector#10]
I really like what you are doing @jfgreffier with this package. I feel that a `near` selector or `closest` would be a great addition. Usually, we are trying to select a unique element. So we don't have to specify the exact location (left, right, above, below). For example, we want to locate the "Sign up" element near/close to the "password" text field.

Another reason for this selector is that the design of the page can change either due to a redesign or, more commonly, a responsive layout change. A near/close selector's functionality would remain unaffected by such a change but if we specify a relative location (left, right, above, below) this would likely break the test.

I think both are needed because sometimes you want to know that the element is indeed located to the left of the design or throw an error but other times you just want to test the functionality that the element just works.

**Comment by jfgreffier** [comment]
Selenium has the near relative locator. They consider an element `near` if it's `50px` away from another.
https://www.selenium.dev/documentation/en/getting_started_with_webdriver/locating_elements/#near

What do you think? `50px` is arbitrary but from my experience with Taiko that has something similar, it's good enough.

How about consider an element near using the reference element size ? Means in the drawing below anything within the green rectangle is `near`
![image](https://user-images.githubusercontent.com/12395973/96041141-a22bc880-0e6b-11eb-8d63-704e40af1926.png)

**Comment by stordopoulos** [comment]
@jfgreffier, I think something like that is a good idea. I don't think there should be too much range to it, otherwise, `near` loses its meaning. For anything further, the rest of the relative selectors would come in place. Do you know if `near` could/should work for elements inside iframes?

**Comment by jfgreffier** [comment]
Hi! I have a time slot to develop `near` and create a release this Thursday.

As for iframes, I didn't think of it. Not sure it works because Playwright's selectors are based on a page or iframe... I guess Playwright chaining suffer the same limitation...
