### ISSUE TITLE
[Fix] The distance should be square pixels instead of a simple one.

### ISSUE THREAD

**Issue by idxn** [jfgreffier/playwright-relative-selector#16]
```
Selector distance should be square pixels (least square method).
This will weight location evenly when multiple relative reference targets.

```
Credit: https://github.com/MarketSquare/robotframework-browser/issues/418#issuecomment-709462515

**Comment by jfgreffier** [comment]
Thanks for the very first Pull Request ! Great work catching the bug as well...

I've used Taiko's algorithm as is. It's not perfect and I guess it will need full rework at some point.
