### ISSUE TITLE
Accurate distance calculation

### ISSUE THREAD

**Issue by jfgreffier** [jfgreffier/playwright-relative-selector#25]
At the moment the distance calculation is a weighted difference of position and size of elements rectangles. It is not mean to be precise, but the distance is wrong if the elements size are very different. The test above does not pass.

```
  it("distance bug", () => {
    const nearBigRight = { x: 5, y: 0, width: 200, height: 20 };
    const farRight = { x: 0, y: 105, width: 20, height: 20 };
    expect(distance(farRight, ref)).toBeGreaterThan(
      distance(nearBigRight, ref)
    );
  });
```

Possibles solutions
- Find rectangles corners and calculate distance between them
- Exact Pythagora https://math.stackexchange.com/a/493365
- Euclidean distance minus a bounding circle

Useful links:
https://math.stackexchange.com/questions/493332/distance-of-two-rectangle-centers-connecting-line-outside-of-the-rectangles
https://en.wikipedia.org/wiki/Taxicab_geometry
https://math.stackexchange.com/questions/78180/finding-closest-rectangle-to-another
https://en.wikipedia.org/wiki/Euclidean_distance#Squared_Euclidean_distance

**Comment by yyvess** [comment]
I think that distance must not be calculated between centrer of elements but between two closer corner.

**Comment by jfgreffier** [comment]
This tool is now deprecated.
