### ISSUE TITLE
Playwright custom selector

### ISSUE THREAD

**Issue by yyvess** [jfgreffier/playwright-relative-selector#35]
Rewrite the module to use Playwright custom selector

Selectors will look like  

- `await page.fill('text="Sign In" >> right=input')`
- `await page.click('text="Sign In" >> right=button')`
- `let elem = await page.waitForSelector('text="candidate text" >> right=text="Reference text"')`

**Comment by jfgreffier** [comment]
v0.1.1 was like that. Please see https://github.com/jfgreffier/playwright-relative-selector/issues/1

My understanding was that chaining operator calls makes it impossible for the custom selector to choose the closest element; and that calling a Playwright selector from a custom selector is not possible.

But maybe your PR solves this.

**Comment by yyvess** [comment]
Features is now implemented natively on Playwright
