### ISSUE TITLE
Near distance must be configurable 

### ISSUE THREAD

**Issue by yyvess** [jfgreffier/playwright-relative-selector#36]
> An element is considered relative to another if the distance between the tow is of 30px or less.

Px depending of the screen resolution, default value must be on EM.

Secondly the value must be configurable.

**Comment by jfgreffier** [comment]
`px` does not depend on the screen resolution only but also of the devicepixelratio. Don't forget that a CSS pixel is not a physical pixel. Also, `em` is relative to a baseline...
https://medium.com/@elad/understanding-the-difference-between-css-resolution-and-device-resolution-28acae23da0b
Selenium and Taiko are using `px`, so I won't change that.

Yes, the value could be configurable.

**Comment by yyvess** [comment]
Features is now implemented natively on Playwright
