### ISSUE TITLE
Error "Cannot read property 'getBoundingClientRect' of undefined" when using relative selector

### ISSUE THREAD

**Issue by klhex** [jfgreffier/playwright-relative-selector#4]
The use of the relative selector in the last statement below causes the following error message:

page.click: Evaluation failed: TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at Object.query (__playwright_evaluation_script__71:1689:35)
    at InjectedScript._querySelectorRecursively (__playwright_evaluation_script__71:698:51)
    at InjectedScript._querySelectorRecursively (__playwright_evaluation_script__71:701:33)
    at InjectedScript.querySelector (__playwright_evaluation_script__71:693:21)
    at eval (__playwright_evaluation_script__73:4:38)
    at onRaf (__playwright_evaluation_script__71:756:37)
    at __playwright_evaluation_script__71:766:13
    at InjectedScript._runAbortableTask (__playwright_evaluation_script__71:824:21)
    at InjectedScript.pollRaf (__playwright_evaluation_script__71:747:21)
    at eval (__playwright_evaluation_script__73:3:25)
=========================== logs ===========================
waiting for selector "text="Mehr erfahren" >> relative=below Premium-Paket"

```javascript
const { selectors, chromium } = require('playwright');

(async () => {
  await selectors.register('relative', require('playwright-relative-selector'));
  const browser = await chromium.launch({
            headless: false,
            slowMo: 50
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.setViewportSize({
      width: 1200,
      height: 1200,
  });
  await page.goto('http://vwfs.de/autoabo.html');
  await page.click('text="Ja, ich willige ein."');
  await page.click('text="Auto Abo abschließen"');
  await page.click(`text="Mehr erfahren" >> relative=below Premium-Paket`);
  await browser.close();
})();
```
Playwright: 1.4.2
node: 14.7.0
OS: MacOS Catalina 10.15.6 (19G2021)

**Comment by jfgreffier** [comment]
Hi!
Thanks for trying my package. At the moment, the text after the position keyword (below) has to exactly match.

As a quick fix, you can use the full text.
```
await page.click(`text="Mehr erfahren" >> relative=below Micro - Premium-Paket`);
```

I'm working on a better version that will make full use of Playwright's selectors, fixing this issue.

**Comment by klhex** [comment]
Thanks for the quick fix information, using the whole string makes it click successfully. 👍

**Comment by jfgreffier** [comment]
Hi, please check version 0.2

It introduce a new syntax and new usage (it's not a selector anymore, but an helper function). This allows you partial text match.

```
const clickMeElement = await relativeSelector(page, 'text="Mehr erfahren" below text="Premium-Paket"');
await clickMeElement.click();
```

I believe it should solve your issue.

**Comment by klhex** [comment]
Yes, that fixes it, thanks!
