### ISSUE TITLE
Dependabot should update package.json

### ISSUE THREAD

**Issue by jfgreffier** [jfgreffier/playwright-relative-selector#40]
Currently, dependabot is only updating dependencies in package-lock.json. It should also update dependencies in `package.json`

**Comment by jfgreffier** [comment]
It might be because of a misunderstanding of dependabot update mechanism. Solution is to, either set more strict version requirement (i.e. ~1.6.0 instead of ^1.6.0) or set the version_requirement_updates excplicitly.

https://dependabot.com/docs/config-file/#version_requirement_updates

**Comment by yyvess** [comment]
The default strategy of Dependabot update only the package-lock.
I change the strategy to 'increase' that will update both.
I update version semantic to patch as Dependabot will update the package.json.
PS. 'Increase' strategy don't care about version constraints on the package.json

**Comment by jfgreffier** [comment]
I close the issue, since you also tested it on you repo. Thanks @yyvess !
