### ISSUE TITLE
Why selector is named 'toRightOf' but 'above' is not 'toAboveOf' or 'aboveOf' ?

### ISSUE THREAD

**Issue by jfgreffier** [jfgreffier/playwright-relative-selector#44]
@jfgreffier 
"Consistency with Selenium and Taiko;"
```
let passwordField = driver.findElement(By.id('password'));
let emailAddressField = await driver.findElements(withTagName('input').above(passwordField));
```
That many code ... I prefer that ;-)
```
let emailAddressField  = await page.waitForSelector('[id="password"] >>  above=input');
```

_Originally posted by @yyvess in https://github.com/jfgreffier/playwright-relative-selector/issues/42#issuecomment-736045874_

**Comment by yyvess** [comment]
I understand you point of view to reuse same keywords of the market.
But first in inconsistent, secondly toRightOf is little bit long ... personally I prefer to have just right.
After we can also support both ?

**Comment by jfgreffier** [comment]
Sorry, I'll persist on this one until there is a bigger demand. I prefer to offer something straight-forward and similar to existing solutions. I find it confusing to have different syntax for the same thing.

If we switch (back) to selector, then the selector can be customized. See this example of custom selector from https://playwright.dev/#version=v1.6.2&path=docs%2Fextensibility.md&q=custom-selector-engines

```
// Register the engine. Selectors will be prefixed with "tag=".
await selectors.register('tag', createTagNameEngine);
```

**Comment by yyvess** [comment]
No worry I agree it's not a priority.
We can close this topic for the moment

**Comment by jfgreffier** [comment]
Thanks for your understanding 🙏
It's my first open-source project with actual contributors, it's difficult to keep my vision and really listen to others. Anyway, thanks for the feedback
